version: '3'

services:
  app:
    image: ghcr.io/pengzhendong/devcontainer:master
    platform: linux/amd64
    container_name: dev
    volumes:
      - ..:/home/vscode/workspace
    ports:
      - "8080:8080"
    command: sleep infinity
